# Generated by Django 6.0.3 on 2026-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('issuer', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('Masters', 'Masters'), ('Bachelor', 'Bachelor'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=20)),
                ('degree_name', models.CharField(help_text='e.g. Master of Design Innovation', max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('achievement', models.CharField(blank=True, help_text='e.g. Summa Cum Laude', max_length=100)),
                ('icon_class', models.CharField(default='bi bi-mortarboard-fill', max_length=60)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if this is the current role', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('skill_tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. Leadership,Strategy,Innovation', max_length=255)),
                ('icon_class', models.CharField(default='bi bi-buildings', help_text='Bootstrap icon class, e.g. bi bi-laptop', max_length=60)),
                ('is_featured', models.BooleanField(default=False, help_text="Show as the highlighted 'Current' card")),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-is_current', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('creative', 'Creative'), ('digital', 'Digital'), ('strategy', 'Strategy'), ('development', 'Development')], max_length=30)),
                ('category_label', models.CharField(blank=True, help_text="Display label shown in the overlay, e.g. 'Creative Design'", max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, help_text='Short teaser shown on the card')),
                ('detail_body', models.TextField(blank=True, help_text='Full description on the detail page')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Full Stack Developer', max_length=100)),
                ('tagline_items', models.CharField(help_text='Comma-separated typed items, e.g. Designer,Developer,Freelancer', max_length=255)),
                ('bio_short', models.TextField(help_text='First paragraph of the About bio')),
                ('bio_long', models.TextField(blank=True, help_text='Second paragraph (optional)')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('hero_bg', models.ImageField(blank=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('awards_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('degree', models.CharField(blank=True, help_text='e.g. Master of Science', max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Portland, OR', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('availability', models.CharField(default='Open to Work', max_length=80)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-code-slash', help_text='Bootstrap icon class, e.g. bi bi-palette', max_length=60)),
                ('is_featured', models.BooleanField(default=False, help_text="Render with the 'Featured' badge")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('detail_body', models.TextField(blank=True, help_text='Full description shown on the service-details page')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. React & Next.js', max_length=100)),
                ('percentage', models.PositiveSmallIntegerField(help_text='0–100')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ['order', '-percentage'],
            },
        ),
    ]
